trigger:
- master
- release/*
pool:
  vmImage: 'Ubuntu-18.04'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: 10
- script: |
    set -o errexit -o pipefail
    npm i
    npm run lint-init
    npm run lint
    npm run build
    npm test
