pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 8.15.1

- script: |
    sudo apt-get update -qq
    sudo apt install -qq libudev-qq

- script: |
    npm run build
    npm test
